### ISSUE TITLE
What can be transfered from device to SDK?

### ISSUE THREAD

**Issue by dashjim** [GO-LiFE/GoFIT_SDK_Android#1]
文档中说“可同步項目”为 步数 睡眠 心率，是不是说血压不支持同步？

下面这个产品叫Care 3支持SDK吗？
https://item.jd.com/17761274289.html#product-detail

**Comment by dashjim** [comment]
Many Thanks!

**Comment by unstory** [comment]
您好，请问这个产品：http://item.jd.com/16016931574.html 的 sdk有提供震动，加速度的接口吗？

**Comment by dashjim** [comment]
http://item.jd.com/15276863338.html 这个应该是Care HR. 请问有care Xc或者XE吗？

**Comment by Robbinsisbatman** [comment]
@dashjim 您好，目前 Care Xc 和 Xe 僅在台灣地區販售。

**Comment by Robbinsisbatman** [comment]
@unstory 您好，這個 sdk 目前尚未提供震動或加速的接口，有特殊需求可以與我們開發人員聯繫。
