### ISSUE TITLE
关于GoWatch的SDK适配性

### ISSUE THREAD

**Issue by zhichenxi** [GO-LiFE/GoFIT_SDK_Android#10]
您好：我想制作的app需要用到心率以外的GPS信息。我想问一下SDK能不能和贵公司的GoWatch产品连接，并获取它的GPS信息？

**Comment by leo19980219** [comment]
我也有相同的問題，想知道SDK能支援GoWatch系列產品那些功能？

**Comment by leo19980219** [comment]
@rik296 了解！謝謝你的回覆
