### ISSUE TITLE
Scan Device無法正常運作

### ISSUE THREAD

**Issue by leo19980219** [GO-LiFE/GoFIT_SDK_Android#12]
我正在測試貴公司的Demo APP "Scan Device"的部分似乎沒有正常運作
有成功初始化SDK 也確定有開啟藍芽

![image](https://user-images.githubusercontent.com/38255570/52177721-3ffa7380-2800-11e9-9f05-10597ed642a3.png)

Logcat出現這些訊息，似乎沒有正常的Scan Device
想知道是哪裡出了問題，謝謝

**Comment by rik296** [comment]
Hi, 您好
scan 不到 device 有以下幾點可以參考：
(1) 手機未開啟定位功能，手機需開啟定位功能，BLE 才能正常運作
(2) 您手邊的裝置與當初申請 SDK license 的裝置不符，請確認一下手邊裝置與申請 lisence 的型號是否相符
(3) 您可能有使用我們的 GoFIT app 連接手環，可以先至 GoFIT app 移除裝置
(4) 手環藍牙功能暫時沒有運作，請接上充電線後長按手環按鍵直到出現 logo 標誌或閃爍一下，重新開機手環，可利用第三方藍牙檢測工具來檢查藍牙訊號，e.g `nRF Connect for Mobile` (https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp)
(5) 手機重開機看看 (可能有用)

**Comment by leo19980219** [comment]
@rik296 你好
(1)～(5)項都確認過了 還是出現一樣的問題
我想是不是D/BluetoothLeScanner出了問題
就Logcat的訊息顯示，程式似乎沒有執行掃描的動作

**Comment by rik296** [comment]
Hi, 您好
這是我的 scan device logcat
![2019-02-13 14 28 34](https://user-images.githubusercontent.com/16934269/52691471-d155ac80-2f9b-11e9-93fc-a3130d96431b.png)

與您的比較起來，在 `D/BluetoothAdapter: startLeScan(): null` 後就出現了差異，系統藍牙應該要偵測到 isLeEnabled(): ON，請問您使用的手機型號與 android 版本是多少呢？我看看能不能有什麼線索來解決這問題

**Comment by leo19980219** [comment]
你好，
我使用的手機是HTC A9
android 版本 6.0.1

**Comment by rik296** [comment]
Hi, 您好
我這邊有使用 HTC one A9 搭配使用您申請的 certificate `client_cert_2de636ddf2b946e285c5a40528974b6e.crt` (裝置是 Care-X HR)，模擬您的環境來測試 scan device，看 logcat 仍然是正常：
![2019-02-14 11 19 27](https://user-images.githubusercontent.com/16934269/52760676-6663ae80-304b-11e9-9351-08967770465e.png)

這邊有幾個方向給您來縮小問題範圍：
(1) 您可以先使用我們的產品化 app `GoFIT` (https://play.google.com/store/apps/details?id=com.golife.fit) 來測試您的手環與手機是否連線正常，若 GoFIT app 也無法掃描到裝置，建議看能不能換支 android 手機來測試看看
(2) 我這邊的 HTC A9 是 android 7.0，看您那邊的版本是否也能升級，或許能解決問題

以上給您參考

**Comment by rik296** [comment]
我剛重看了您提供的 logcat，發現 debug level 皆為 D，您可以檢查一下 debug level 並調整為 Verbose，或許 logcat 就會 dump 出 scan 資訊 (我們 demo app 的 debug message 是 Info)

**Comment by leo19980219** [comment]
你好，
我已經將android升級至7.0，debug level 也調整為 Verbose
但依然掃描不到手環
logcat會先出現
com.goyourlife.gofit_demo D/BluetoothAdapter: STATE_ON
com.goyourlife.gofit_demo D/BluetoothLeScanner: onClientRegistered() - status=0 clientIf=6
過大約10秒再出現
com.goyourlife.gofit_demo D/BluetoothAdapter: stopLeScan()
com.goyourlife.gofit_demo D/BluetoothAdapter: STATE_ON
![image](https://user-images.githubusercontent.com/38255570/52893927-bfaf1780-31dc-11e9-88c8-2516dffb4333.png)

PS.使用你們的產品化app可以正常掃描與配對到手環

**Comment by leo19980219** [comment]
我想會不會跟SDK init的部分有關係
我按下SDK init/reinit 有錯誤訊息
![image](https://user-images.githubusercontent.com/38255570/52894188-b9229f00-31e0-11e9-8b50-d38145a19b92.png)

**Comment by rik296** [comment]
Hi, 請問您使用完產品化 app 後，有先移除手環裝置嗎？也就是手環上的藍牙狀態要是 X，之後再用 Demo app 來 scan device 😀

**Comment by rik296** [comment]
> 我想會不會跟SDK init的部分有關係
> 我按下SDK init/reinit 有錯誤訊息
> ![image](https://user-images.githubusercontent.com/38255570/52894198-d48daa00-31e0-11e9-8929-e0c2c29ea56c.png)

這個 doAAA() 有 exception，請問您手機的網路有正常運作嗎？

**Comment by leo19980219** [comment]
有先移除了，手環上的藍牙狀態也是 X

**Comment by leo19980219** [comment]
你好，問題已排除了
問題出在SDK init的部分沒有成功導致scan device api沒辦法正常運行
謝謝你
