### ISSUE TITLE
SDK init Error : Missing `certificate`

### ISSUE THREAD

**Issue by leo19980219** [GO-LiFE/GoFIT_SDK_Android#14]
當我使用GoFITSdk.getInstance時出現Missing `certificate`的錯誤
![image](https://user-images.githubusercontent.com/38255570/52896206-69070500-31ff-11e9-8cd2-9797c185830e.png)
也已經將收到的驗證文件更名並放到我創建project的assets資料夾裡
想請問還有哪些可能導致這個錯誤的原因
謝謝

**Comment by rik296** [comment]
Hi, 請參考以下的路徑存放 certificate 
<img width="478" alt="2019-02-16 15 41 00" src="https://user-images.githubusercontent.com/16934269/52896347-9c4a9380-3201-11e9-940b-4e3cce12df8f.png">

在 MainActivity.java 的 onCreate() function 中，有一段讀檔的 code，請將 input file 的檔名改為與您的 certificate file 一致
```
// Read certificate from file
        sdk_certificate = null;
        try {
            // file name
            InputStream inputstream = this.getAssets().open("client_cert_2de636ddf2b946e285c5a40528974b6e.crt"); 
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputstream));
            StringBuilder sb = new StringBuilder();
            String line = null;
            while ((line = reader.readLine()) != null) {
                sb.append(line).append("\n");
            }
            reader.close();
            sdk_certificate = sb.toString();
        }
        catch (Exception e) {
            Log.e(_tag, e.toString());
            showToast("Exception : " + e.toString());
        }
```

**Comment by leo19980219** [comment]
@rik296 謝謝你，照著你的方式問題解決了
