### ISSUE TITLE
doSyncFitnessData  onFailure: bind service timeout

### ISSUE THREAD

**Issue by leo19980219** [GO-LiFE/GoFIT_SDK_Android#15]
你好，
我在使用doSyncFitnessData的api時出現onFailure: bind service timeout的錯誤errorCode=700
程式跟手環也有正常的連線
想請問有甚麼可能導致出現這個錯誤？
謝謝

**Comment by rik296** [comment]
Hi, 這個問題有幾個部分需要確認一下：
(1) 您使用 doSyncFitnessData API 是在您自己開發的 app 上或是我們附的 demo app ?
(2) 這個 error 是偶發出現或是必發生？
(3) 若是您在自己開發的 app 上使用，請確認一下您的 AndroidManifest.xml 的 application tag 中是否有加上 
```
<service
        android:name="com.golife.service.SyncService"
        android:enabled="true" />
```
(4) 若是用我們的 demo app，在按下 Get Fitness Data 後，請等待數字跑完再進行下一個操作

**Comment by leo19980219** [comment]
你好，加入service之後已解決問題，謝謝
