### ISSUE TITLE
是否有支援偵測手環上的按鈕被按下？

### ISSUE THREAD

**Issue by leo19980219** [GO-LiFE/GoFIT_SDK_Android#17]
你好，
我們想開發一個警訊系統，希望能雙擊下手環上的按鈕後讓手機收到一個訊號，對伺服器發出警訊
請問貴公司的 API 是否有支援偵測按鈕事件的功能？
謝謝

**Comment by rik296** [comment]
Hi, 目前我們的 API 尚未有單獨偵測按鈕事件的功能，若您的專案有客製化的需求，歡迎您參考我們的[商業方案](http://dev.goyourlife.com/)，謝謝！

**Comment by leo19980219** [comment]
@rik296 了解！謝謝你的回覆
