### ISSUE TITLE
重連疑問

### ISSUE THREAD

**Issue by shuanme** [GO-LiFE/GoFIT_SDK_Android#20]
想請問，當手環因距離太遠而斷線，重新靠近時想要重新配對，應當套用甚麼函式?是使用doConnectDevice嗎?(自己測試時執行到doConnectDevice就出現閃退問題)

**Comment by shuanme** [comment]
> 想請問，當手環因距離太遠而斷線，重新靠近時想要重新配對，應當套用甚麼函式?是使用doConnectDevice嗎?(自己測試時執行到doConnectDevice就出現閃退問題)

**Comment by rik296** [comment]
Hi, 若已經有先前的配對資訊，斷線後欲再連上是使用 doConnectDevice() 沒錯，關於閃退問題，您可以附上 logcat 資訊，我們來分析看看問題在哪

**Comment by shuanme** [comment]
我在MainActivity裡記住手環資訊，然後另開一個BackGroundService作背景服務，並在裡面呼叫doConnectDevice()函式

MainActivity的_goFITSdk.doConfirmPairingCode內: 

   	 __goFITSdk.getDeviceMAC(new GoFITSdk.GetDeviceInfoCallback() {
	    @Override
	    public void onSuccess(String s) {
	        mac = s;
	        SharedPreferences setting_watch =getSharedPreferences("watch_info",MODE_PRIVATE);

	        setting_watch.edit().putString("macAddress",mac)
	                .putString("productID",ScanResult.getProductID())
	                .putString("pairingCode",newcode)
	                .putString("pairingTime",s1)
	                .commit();
	        
	        Log.d("MAIN", mac+"_"+ScanResult.getProductID()+"_"+newcode+"_"+s1);
	    }

	    @Override
	    public void onFailure(int i, String s) {
	    }
	});


BackGroundService:

	if(!_goFITSdk.isBLEConnect()){
	    Log.d("GPS", "Start");

	    SharedPreferences setting_watch =getSharedPreferences("watch_info",MODE_PRIVATE);
	    String macAddress = setting_watch.getString("macAddress", "");
	    String productID = setting_watch.getString("productID", "");
	    String pairingCode = setting_watch.getString("pairingCode", "");
	    String pairingTime = setting_watch.getString("pairingTime", "");
	    Log.d("GPS", "macAddress: "+ macAddress+"-"+productID+"-"+pairingCode+"-"+pairingTime);
	    try {

	        _goFITSdk.doConnectDevice(macAddress, productID, pairingCode, pairingTime, new GoFITSdk.GenericCallback() {
	            @Override
	            public void onSuccess() {
	                Log.d("GPS", "onSuccess: ");
	            }

	            @Override
	            public void onFailure(int i, String s) {
	                Log.d("GPS", "onFailure: " + s);
	            }
	        });
	    }catch (Exception e){
	        Log.d("GPS", "E"+e.getMessage());
	    }
	    Log.d("GPS", "BLE connect fail in Thread");
	}

logcat:
![image](https://user-images.githubusercontent.com/34371553/56105656-eb961180-5f6f-11e9-89cc-5b9928cbc3dc.png)

**Comment by rik296** [comment]
Hi, 這看起來像是 doConnectDevice() 時給的參數出現問題，導致了 array out of boundary，可否提供一下

macAddress
pairingCode
pairingTime
productID

這幾個值給我們看一下？

**Comment by shuanme** [comment]
您好，我大概知道問題所在了，看了一下demo程式碼，發現文件上參數的順序是錯誤的，目前已經可以重新連線了。

還有個問題，我希望使用者每次開APP不用一直scan配對連線，想請問我如果配對過一次，讓手機記住手環資訊，下次連線時能否直接使用doConnectDevice()連線。

**Comment by rik296** [comment]
Hi, 
1. 原來如此，文件上的錯誤我們會在著手修正，感謝！
2. 沒錯，doConnectDevice() 就是用在讓使用者在配對過的情況下，下一次能快速再連上的情境

**Comment by shuanme** [comment]
感謝您的答覆，我會再研究看看
