### ISSUE TITLE
鬧鐘功能

### ISSUE THREAD

**Issue by shuanme** [GO-LiFE/GoFIT_SDK_Android#23]
想請問這個手環是否有鬧鐘功能?若有是如何呈現的，以及這個SDK的鬧鐘code該如何使用?

**Comment by rik296** [comment]
Hi, 手環有鬧鐘功能，可以參考我們的 wiki 文件 "Device Settings" 章節：
https://github.com/GO-LiFE/GoFIT_SDK_Android/wiki/GoFIT-SDK-Android-Application-Programming-Interface-Specifications#device-settings

也可參考我們的 demo app "Device Setting" 的功能，以及 demoSettingAlarmClock() 這個 function

**Comment by shuanme** [comment]
想請問一下，我看了一下輸入格式，想請問以下參數分別代表甚麼意思:
`[on/off], [index(0~29)], [repeatDays(0~127 bit operator)], [HH:mm], [category]`

**Comment by rik296** [comment]
Hi, 

[on/off] => 代表開關

[index(0~29)] => 代表 鬧鐘 index，可設定 0~29 共 30 組鬧鐘

[repeatDays(0~127 bit operator)] => 代表重複響的星期
bit0 : Sun
bit1 : Mon
bit2 : Tue
bit3 : Wed
bit4 : Thu
bit5 : Fri
bit6 : Sat
例如此鬧鐘要設定為 每個星期一~星期五 都要響，就要設定為 62 = (0111110) 

[HH:mm] => 代表鬧鐘響的時間，例如：15:13, 20:15, 07:45 等等

[category] => 表示鬧鐘的種類，有以下幾種：
// 0 : wake up (起床) 
// 1 : sleep (就寢)
// 2 : meeting (會議) 
// 3 : training (訓練) 
// 4 : dating (約會) 
// 5 : party (派對) 
// 6 : others (其他) 
// 7 : medicine (用藥提醒)
