### ISSUE TITLE
請問一下可不可以取得手環中顯示的總步數?

### ISSUE THREAD

**Issue by jameslee5656** [GO-LiFE/GoFIT_SDK_Android#26]
在文件中的 getSteps
public class TableStepRecord {
    public Date getTimestamp()    // Unix Time, i.e., number of `milliseconds` that have elapsed since 00:00:00 UTC time, 1 January 1970
    public int getSteps()
    public int getCalories()
    public int getDistance()
}
就我們的理解以及應用時，這是手環一段時間內的步數，而非手環顯示的總步數

**Comment by rik296** [comment]
Hi, 目前 SDK 僅提供一段時間區間內的步數, 熱量, 距離統計，您可以將這些時間區間的紀錄加總即可獲得當前手環顯示之步數

**Comment by shuanme** [comment]
所以說 手環所呈現的總步數是手環內部自己去加總的?還有個問題，請問手環步數, 熱量, 距離統計是在甚麼時間會規0

**Comment by rik296** [comment]
Hi, 手環面板的資訊在午夜 12 點會歸零，但是詳細的步數、熱量、距離是會一直保存到您有執行 doClearDeviceData() 這個 api 後才會清除

**Comment by jameslee5656** [comment]
謝謝
