### ISSUE TITLE
震動疑問

### ISSUE THREAD

**Issue by shuanme** [GO-LiFE/GoFIT_SDK_Android#27]
目前嘗試只有顯示文字時會附加震動功能，想請問可以單獨讓手環震動嗎?有震動的函式嗎?

**Comment by rik296** [comment]
Hi, 若您的手環為 Care-Xe 或 Care-Xc，可使用 "尋找手環" 功能讓手環單獨震動，可參考文件：
https://github.com/GO-LiFE/GoFIT_SDK_Android/wiki/GoFIT-SDK-Android-Application-Programming-Interface-Specifications#find-my-care
