### ISSUE TITLE
如何啟動Demo APP

### ISSUE THREAD

**Issue by s1013660s** [GO-LiFE/GoFIT_SDK_Android#28]
按照官網之安裝步驟安裝完後，開啟android studio，無法執行run圖示，
請問是有哪一個步驟出錯嗎?謝謝。
![android_studio](https://user-images.githubusercontent.com/50609688/57745058-3ab19c80-76fe-11e9-8690-65d95f6c230f.PNG)

**Comment by rik296** [comment]
Hi, 請先點開您截圖右下方的 Event Log，這邊會顯示您目前 IDE 有遇到哪些問題，我們可以一個一個來排除

**Comment by s1013660s** [comment]
你好:
附圖是執行結果，麻煩你了。
![擷取](https://user-images.githubusercontent.com/50609688/57745842-4e123700-7701-11e9-9c20-aa5716e25b4b.PNG)

**Comment by rik296** [comment]
Hi, 看 error 敘述應該是您的模擬器設定有點問題，您可以打開您的 AVD Manager 檢查一下，
在上方 Tab > Tools > AVD Manager，另外說明一下，我們的 SDK 因為是要連線藍牙裝置，沒有提供模擬器使用的 library，所以必須運行在 Android 的實機上

**Comment by s1013660s** [comment]
附圖是模擬器的設定，請問需要改些什麼地方?
還是AVD Manager提供的模擬器皆不能run，
另外請問如何在Android實機上開啟
![擷取](https://user-images.githubusercontent.com/50609688/57746839-8ddb1d80-7705-11e9-9515-13d55df95633.PNG)

**Comment by rik296** [comment]
Hi, 先跟您確認一下您的 android studio 版本是多少？
可以從上方 tab bar > About Android Studio 看到，目前最新版應該是 3.4

**Comment by s1013660s** [comment]
是3.4，如附圖
![擷取](https://user-images.githubusercontent.com/50609688/57747314-9a607580-7707-11e9-8cb2-48d56ca62e42.PNG)

**Comment by rik296** [comment]
Hi, 網路上有些相關資訊，供您參考，看看有沒有幫助：
https://stackoverflow.com/questions/55328499/emulator-emulator-error-running-multiple-emulators-with-the-same-avd-is-an-ex
https://stackoverflow.com/questions/12150567/can-not-run-two-or-multiple-android-emulator-at-the-same-time
https://windows-hexerror.linestarve.com/q/so47631771-Emulator-Process-finished-with-exit-code-1073741819-0xC0000005

**Comment by s1013660s** [comment]
關於run圖示啟動問題，按照參考網址(https://blog.csdn.net/purple_lumpy/article/details/51982622)操作後，如圖顯示錯誤，請問是哪個環節出錯，謝謝
![擷取](https://user-images.githubusercontent.com/50609688/57909929-a0488900-78b6-11e9-9890-43b0f227a04a.PNG)

**Comment by rik296** [comment]
Hi, 請問您紅線框的部分，有依照指示關閉嗎？
![57909929-a0488900-78b6-11e9-9890-43b0f227a04a](https://user-images.githubusercontent.com/16934269/57992163-63aea480-7ae5-11e9-96a7-7b3b3820a527.png)

**Comment by s1013660s** [comment]
關閉後，再次按下sync project with gradles files，跑出以下視窗。
![擷取](https://user-images.githubusercontent.com/50609688/57992586-8e99f800-7ae7-11e9-8a0f-1933edbb1d67.PNG)

**Comment by rik296** [comment]
你到上方 Tab bar -> Help -> Show Log 看看發生什麼錯誤

**Comment by s1013660s** [comment]
點開Show Log in Explorer後跳至.AndroidStudio3.4 -> system ->log，看起來是lateinit屬性bundleFile尚未初始化?
![擷取](https://user-images.githubusercontent.com/50609688/57993539-02d69a80-7aec-11e9-8cf8-43a316242c77.PNG)

**Comment by s1013660s** [comment]
調整File -> settings中Gradle設定後，如圖。
問題顯示轉為下圖紅框，請問有哪一個地方需要調整嗎?謝謝。
![擷取](https://user-images.githubusercontent.com/50609688/58086130-a01af700-7bf0-11e9-9788-66b8d5163f41.PNG)

![擷取](https://user-images.githubusercontent.com/50609688/58085875-26830900-7bf0-11e9-8221-bfcc0931a7f7.PNG)

**Comment by rik296** [comment]
Hi, 因為您遇到的大多是 IDE 環境設定問題，我們這邊沒辦法一一去檢視每項設定，還是您方便參考以下幾種方法來解決目前的問題：
1. 我們這邊能成功運行的 android studio 版本為 3.2.1，您可以試著將 IDE 版本降版為 3.2.1 看看
2. 您可以將您目前的專案放上 GitHub，我這邊將它 fork 過來運行看看
3. 您可安裝 teamviewer 之類的遠端軟體，我們透過遠端桌面的方式來幫您解決看看

**Comment by s1013660s** [comment]
我已將IDE版本降至3.2.1, 還是無法解決，以下是專案zip檔，麻煩你執行看看，謝謝

[GoFIT_SDK_Android-1.4_2018-11-28-1.zip](https://github.com/GO-LiFE/GoFIT_SDK_Android/files/3205182/GoFIT_SDK_Android-1.4_2018-11-28-1.zip)

**Comment by rik296** [comment]
Hi, 經查看設定環境，可以修改以下兩個檔案的參數：
1. /GoFIT_SDK_Android-1.4_2018-11-28/GoFIT_SDK_Demo/build.gradle
   ```
   classpath 'com.android.tools.build:gradle:3.2.1'
   ```
2. /GoFIT_SDK_Android-1.4_2018-11-28/GoFIT_SDK_Demo/gradle/wrapper/gradle-wrapper.properties
   ```
   distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
   ```
以下修改過的專案給您參考：
[GoFIT_SDK_Android-1.4_2018-11-28-revise.zip](https://github.com/GO-LiFE/GoFIT_SDK_Android/files/3206279/GoFIT_SDK_Android-1.4_2018-11-28-revise.zip)

**Comment by s1013660s** [comment]
感謝，成功燒錄程式至實機了
