### ISSUE TITLE
手環連接後，如何設定相關個人訊息?

### ISSUE THREAD

**Issue by larryvisuals** [GO-LiFE/GoFIT_SDK_Android#35]
該手環SDK是否有提供可以設定姓別、身高、體重等個人訊息的函數?

**Comment by rik296** [comment]
您好！目前 android SDK 尚未開放設定身高、體重等個人資訊功能，若您有客製化需求，歡迎參考我們的正式版方案，或與我們業務窗口聯繫：
hayes.chen@goyourlife.com

**Comment by larryvisuals** [comment]
請問正式版方案是指會有提供另外的SDK，但是方案費用會較高嗎?

**Comment by rik296** [comment]
是的，正式版方案授權時間比試用版長，也可客製化 API 功能，歡迎參考：
http://dev.goyourlife.com/
